"""initial migration

Revision ID: 2854fc568b35
Revises: None
Create Date: 2015-04-15 18:51:53.074761

"""

# revision identifiers, used by Alembic.
revision = '2854fc568b35'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
