"""empty message

Revision ID: 2ce818ebc5fe
Revises: 67af33fd9aa
Create Date: 2015-04-19 13:39:51.404673

"""

# revision identifiers, used by Alembic.
revision = '2ce818ebc5fe'
down_revision = '67af33fd9aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body_html')
    ### end Alembic commands ###
