"""empty message

Revision ID: 3090741f0ea0
Revises: d7a5e7492aa
Create Date: 2015-04-18 21:02:05.072316

"""

# revision identifiers, used by Alembic.
revision = '3090741f0ea0'
down_revision = 'd7a5e7492aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
