"""empty message

Revision ID: 31ba0d57fed1
Revises: 3cde44cf359a
Create Date: 2015-04-19 10:25:04.944840

"""

# revision identifiers, used by Alembic.
revision = '31ba0d57fed1'
down_revision = '3cde44cf359a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
