"""empty message

Revision ID: 441104829b2c
Revises: ae0ffdd2b7a
Create Date: 2015-04-17 16:38:10.376634

"""

# revision identifiers, used by Alembic.
revision = '441104829b2c'
down_revision = 'ae0ffdd2b7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
