"""empty message

Revision ID: 4a484e803d1d
Revises: 671bdb9616e
Create Date: 2015-04-17 20:47:21.379876

"""

# revision identifiers, used by Alembic.
revision = '4a484e803d1d'
down_revision = '671bdb9616e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'member_since')
    op.drop_column('roles', 'about_me')
    op.drop_column('roles', 'location')
    op.drop_column('roles', 'last_seen')
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    op.add_column('roles', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('roles', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.add_column('roles', sa.Column('about_me', sa.TEXT(), nullable=True))
    op.add_column('roles', sa.Column('member_since', sa.DATETIME(), nullable=True))
    ### end Alembic commands ###
