"""empty message

Revision ID: 4eba370fc2d
Revises: 2e552bb25830
Create Date: 2015-04-19 19:11:43.747294

"""

# revision identifiers, used by Alembic.
revision = '4eba370fc2d'
down_revision = '2e552bb25830'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
