"""empty message

Revision ID: 4f5da5357554
Revises: f7d4f0ab69b
Create Date: 2015-04-18 20:15:02.130761

"""

# revision identifiers, used by Alembic.
revision = '4f5da5357554'
down_revision = 'f7d4f0ab69b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
