"""empty message

Revision ID: 558752b3d43b
Revises: 4eba370fc2d
Create Date: 2015-04-19 20:52:17.033238

"""

# revision identifiers, used by Alembic.
revision = '558752b3d43b'
down_revision = '4eba370fc2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
