"""empty message

Revision ID: 5fa643ae964
Revises: 3090741f0ea0
Create Date: 2015-04-18 22:09:55.240094

"""

# revision identifiers, used by Alembic.
revision = '5fa643ae964'
down_revision = '3090741f0ea0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
