"""empty message

Revision ID: 671bdb9616e
Revises: 8f4ddfbf884
Create Date: 2015-04-17 20:41:32.206755

"""

# revision identifiers, used by Alembic.
revision = '671bdb9616e'
down_revision = '8f4ddfbf884'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
