"""empty message

Revision ID: 67af33fd9aa
Revises: 31ba0d57fed1
Create Date: 2015-04-19 11:36:38.211215

"""

# revision identifiers, used by Alembic.
revision = '67af33fd9aa'
down_revision = '31ba0d57fed1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
