"""empty message

Revision ID: 8f4ddfbf884
Revises: 1fb6e528ca58
Create Date: 2015-04-17 20:07:52.837705

"""

# revision identifiers, used by Alembic.
revision = '8f4ddfbf884'
down_revision = '1fb6e528ca58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
