"""empty message

Revision ID: d7a5e7492aa
Revises: 4f5da5357554
Create Date: 2015-04-18 20:18:50.648095

"""

# revision identifiers, used by Alembic.
revision = 'd7a5e7492aa'
down_revision = '4f5da5357554'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
