"""empty message

Revision ID: f7d4f0ab69b
Revises: 3fba5022fa35
Create Date: 2015-04-18 19:07:15.763164

"""

# revision identifiers, used by Alembic.
revision = 'f7d4f0ab69b'
down_revision = '3fba5022fa35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
